sudo: required
services:
- docker
language: bash
jobs:
  include:
    - stage: base
      script: ./travis_build_base_image.sh

    - stage: python
      script:
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - docker login -u="$DOCKER_JC_USER" -p="$DOCKER_JC_PASS"
        - docker build -f docker/arm/Dockerfile-python -t johncclayton/electric-pi-python .
        - docker push johncclayton/electric-pi-python

    - stage: build images
      script: SERVICE=web ./travis_build_docker_image.sh
    -
      script: SERVICE=worker ./travis_build_docker_image.sh

    - stage: build SD image
      env:
        - YAY=$TRAVIS_BRANCH
      script: ./travis_webhook_to_build_sd_image.sh
